### ISSUE TITLE
"Unterminated string", unknown identifier for locals

### ISSUE THREAD

**Issue by Gama11** [ncannasse/hashlink-debugger#11]
When hovering over the string in `trace("Test")`, I get this confusing message:

![](https://i.imgur.com/augF9LI.png)

"Unterminated" means what exactly? It's not like you need to add a trailing `\0` in Haxe strings like in C. ;)

Also, it seems showing the value for locals doesn't work ("Unknown identifier s")?

![](https://i.imgur.com/rV0R6IX.png)

`s` exists in the output with `-D dump=pretty`, so it's not inlined by the analyzer or anything.

**Comment by ncannasse** [comment]
Unterminated string: not sure what VSCode is sending to HLAdapter for evaluation, but it seems it's missing a " (the expression is parsed with hscript :D)

Unknown identifier: that's a bit tricky. in the Dump you can look at `hlopt.txt` , we store the locals set per opcode (third column `set s` for example). But because of optimization it might be removed so we are losing the local/register mapping. I need to work on improving this but it's a bit difficult.

**Comment by Gama11** [comment]
Moved to https://github.com/vshaxe/hashlink-debugger/issues/1 and https://github.com/vshaxe/hashlink-debugger/issues/2.
